LANG_BY_EXT = {
    ".go": ("Go", "#00ADD8"),
    ".py": ("Python", "#3572A5"),
    ".ipynb": ("Jupyter Notebook", "#DA5B0B"),
    ".js": ("JavaScript", "#F1E05A"),
    ".mjs": ("JavaScript", "#F1E05A"),
    ".cjs": ("JavaScript", "#F1E05A"),
    ".ts": ("TypeScript", "#3178C6"),
    ".tsx": ("TypeScript", "#3178C6"),
    ".jsx": ("JavaScript", "#F1E05A"),
    ".vue": ("Vue", "#41B883"),
    ".java": ("Java", "#B07219"),
    ".kt": ("Kotlin", "#A97BFF"),
    ".kts": ("Kotlin", "#A97BFF"),
    ".c": ("C", "#555555"),
    ".h": ("C/C++ Header", "#555555"),
    ".cpp": ("C++", "#F34B7D"),
    ".cc": ("C++", "#F34B7D"),
    ".cxx": ("C++", "#F34B7D"),
    ".hpp": ("C++", "#F34B7D"),
    ".cs": ("C#", "#178600"),
    ".rs": ("Rust", "#DEA584"),
    ".html": ("HTML", "#E34C26"),
    ".htm": ("HTML", "#E34C26"),
    ".css": ("CSS", "#563D7C"),
    ".scss": ("SCSS", "#C6538C"),
    ".sass": ("Sass", "#A53B70"),
    ".less": ("Less", "#1D365D"),
    ".sh": ("Shell", "#89E051"),
    ".bash": ("Shell", "#89E051"),
    ".zsh": ("Shell", "#89E051"),
    ".ps1": ("PowerShell", "#012456"),
    ".yaml": ("YAML", "#CB171E"),
    ".yml": ("YAML", "#CB171E"),
    ".json": ("JSON", "#292929"),
    ".toml": ("TOML", "#9C4221"),
    ".xml": ("XML", "#0060AC"),
    ".md": ("Markdown", "#083FA1"),
    ".tex": ("TeX", "#3D6117"),
    ".r": ("R", "#198CE7"),
    ".rb": ("Ruby", "#701516"),
    ".php": ("PHP", "#4F5D95"),
    ".swift": ("Swift", "#F05138"),
    ".dart": ("Dart", "#00B4AB"),
    ".lua": ("Lua", "#000080"),
    ".gd": ("GDScript", "#355570"),
    ".dockerfile": ("Dockerfile", "#384D54"),
}

NAME_BY_FILENAME = {
    "Dockerfile": ("Dockerfile", "#384D54"),
    "Makefile": ("Makefile", "#427819"),
    "CMakeLists.txt": ("CMake", "#DA3434"),
}

DEFAULT_IGNORE = [
    ".git/**",
    ".github/**",
    "node_modules/**",
    "vendor/**",
    "dist/**",
    "build/**",
    "target/**",
    "coverage/**",
    ".next/**",
    ".nuxt/**",
    ".vite/**",
    ".venv/**",
    "venv/**",
    "__pycache__/**",
    "*.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "Cargo.lock",
    "go.sum",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.svg",
    "*.ico",
    "*.pdf",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.7z",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.mp3",
    "*.wav",
    "*.onnx",
    "*.pt",
    "*.pth",
]

OTHER_COLOR = "#d1d7de"
TRACK_COLOR = "#eff2f5"
